name: Test DB Connections

# Trigger the workflow manually with a dropdown to choose the environment
on:
  workflow_dispatch: # Manual trigger only
    inputs:
      environment:
        description: "Target environment"
        required: true
        type: environment

jobs:
  execute-sql:
    name: Deploy CDCR packages for ${{ github.event.inputs.environment }}
    runs-on: ubuntu-latest
    environment:
      name: ${{ inputs.environment}}

    # Permissions needed to use GitHub OIDC and read the repo
    permissions:
      id-token: write
      contents: read
    
    # Define commonly used environment variables
    env:
      AWS_REGION: eu-west-2

    steps:

    # Setup steps
    # Check out CDCR repository
    - name: Checkout Repository
      uses: actions/checkout@v4

    # Assume the AWS role in shared-services using GitHub OIDC
    # This gives the workflow permission to assume deployment roles in other accounts
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v4.0.2
      with:
        role-to-assume: ${{ vars.AWS_ROLE }}
        role-session-name: cdc-replacement-gha-${{ github.run_number }}
        aws-region: ${{ env.AWS_REGION }}


    - name: Start Port Forwarding
      uses: ./.github/actions/ssm-port-forwarding
      with:
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}

    - name: Install SQLcl 
      uses: ./.github/actions/install-sqlcl

    # Deployment steps
    
    - name: 1 - Test DB Connection
      uses: ./.github/actions/execute-sql
      with:
        DB_USERNAME: ${{ secrets.BUILD_USER }}
        DB_PASSWORD: ${{ secrets.BUILD_PASSWORD }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_SID: ${{ secrets.DB_SID }}
        SQL_FILE: ${{ github.workspace }}/cdcr/database/scripts/test_db_connection.sql
  
